# Generated by Django 2.2.6 on 2020-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
